require("configs/settings")
require("configs/monitors")
require("configs/keybinds")
require("configs/windowrules")
require("configs/workspaces")
require("configs/animations")
require("configs/autostart")
require("configs/env")
-- For Noctalia Color templates
require("noctalia").apply_theme()
